name: MLSec_Project
channels:
  - pytorch
  - anaconda
  - nvidia
  - defaults
dependencies:
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=25.1.0=py312h02ab6af_0
  - asttokens=3.0.0=py312haa95532_0
  - async-lru=2.0.5=py312haa95532_0
  - attrs=25.4.0=py312haa95532_2
  - babel=2.17.0=py312haa95532_0
  - blas=1.0=mkl
  - bleach=6.3.0=py312haa95532_0
  - brotlicffi=1.1.0.0=py312h885b0b7_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - certifi=2025.11.12=py312haa95532_0
  - cffi=2.0.0=py312h02ab6af_1
  - charset-normalizer=3.4.4=py312haa95532_0
  - colorama=0.4.6=py312haa95532_0
  - comm=0.2.3=py312haa95532_0
  - cuda-cccl=13.0.85=h5221881_1
  - cuda-cccl_win-64=13.0.85=hc667259_1
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=13.0.85=h17533db_0
  - cuda-opencl-dev=13.0.85=hde976d8_0
  - cuda-profiler-api=13.0.85=h5221881_0
  - cuda-runtime=12.1.0=0
  - cuda-version=13.0=3
  - debugpy=1.8.16=py312h885b0b7_1
  - decorator=5.2.1=py312haa95532_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - executing=2.2.1=py312haa95532_0
  - expat=2.7.3=h9214b88_0
  - filelock=3.20.0=py312haa95532_0
  - freetype=2.13.3=h0620614_0
  - giflib=5.2.2=h7edc060_0
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.1=py312h827c3e9_0
  - h11=0.16.0=py312haa95532_1
  - html5lib=1.1=pyhd3eb1b0_0
  - httpcore=1.0.9=py312haa95532_0
  - httpx=0.28.1=py312haa95532_1
  - idna=3.11=py312haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.31.0=py312h4442805_0
  - ipython=9.7.0=py312haa95532_0
  - ipython_pygments_lexers=1.1.1=py312haa95532_0
  - ipywidgets=8.1.7=py312haa95532_0
  - jedi=0.19.2=py312haa95532_0
  - jinja2=3.1.6=py312haa95532_0
  - jpeg=9f=ha349fce_0
  - json5=0.12.1=py312haa95532_0
  - jsonschema=4.25.0=py312haa95532_1
  - jsonschema-specifications=2025.9.1=py312haa95532_0
  - jupyter=1.1.1=py312haa95532_0
  - jupyter-lsp=2.2.5=py312haa95532_0
  - jupyter_client=8.6.3=py312haa95532_1
  - jupyter_console=6.6.3=py312haa95532_1
  - jupyter_core=5.9.1=py312haa95532_0
  - jupyter_events=0.12.0=py312haa95532_0
  - jupyter_server=2.16.0=py312haa95532_0
  - jupyter_server_terminals=0.5.3=py312haa95532_0
  - jupyterlab=4.5.0=py312haa95532_0
  - jupyterlab_pygments=0.3.0=py312haa95532_0
  - jupyterlab_server=2.28.0=py312haa95532_0
  - jupyterlab_widgets=3.0.15=py312haa95532_0
  - khronos-opencl-icd-loader=2025.07.22=h79b28c9_0
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcurand=10.4.0.35=h86a452a_1
  - libcurand-dev=10.4.0.35=hde976d8_1
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_1
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libpng=1.6.50=h46444df_0
  - libsodium=1.0.20=h83e8143_0
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h3d04722_1
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=3.0.2=py312h827c3e9_0
  - matplotlib-inline=0.2.1=py312haa95532_0
  - mistune=3.1.2=py312haa95532_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py312h827c3e9_2
  - mkl_fft=1.3.11=py312h827c3e9_0
  - mkl_random=1.2.8=py312h0158946_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py312haa95532_0
  - nbclient=0.10.2=py312haa95532_0
  - nbconvert=7.16.6=py312haa95532_0
  - nbconvert-core=7.16.6=py312haa95532_0
  - nbconvert-pandoc=7.16.6=py312haa95532_0
  - nbformat=5.10.4=py312haa95532_0
  - nest-asyncio=1.6.0=py312haa95532_0
  - networkx=3.5=py312haa95532_0
  - notebook=7.5.0=py312haa95532_0
  - notebook-shim=0.2.4=py312haa95532_0
  - numpy=2.3.1=py312h5f75535_0
  - numpy-base=2.3.1=py312h23d94f8_0
  - opencl-headers=2025.07.22=h885b0b7_0
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.0.18=h543e019_0
  - overrides=7.7.0=py312haa95532_0
  - packaging=25.0=py312haa95532_1
  - pandoc=3.8=haa95532_0
  - pandocfilters=1.5.1=py312haa95532_0
  - parso=0.8.5=py312haa95532_0
  - pillow=11.1.0=py312h096bfcc_0
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.0=py312haa95532_0
  - prometheus_client=0.21.1=py312haa95532_0
  - prompt-toolkit=3.0.52=py312haa95532_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py312h02ab6af_1
  - pure_eval=0.2.3=py312haa95532_0
  - pycparser=2.23=py312haa95532_0
  - pygments=2.19.2=py312haa95532_0
  - pysocks=1.7.1=py312haa95532_1
  - python=3.12.12=h716150d_1
  - python-dateutil=2.9.0post0=py312haa95532_2
  - python-fastjsonschema=2.21.2=py312haa95532_0
  - python-json-logger=4.0.0=py312haa95532_0
  - pytorch=2.5.1=py3.12_cuda12.1_cudnn9_0
  - pytorch-cuda=12.1=hde6ce7c_6
  - pytorch-mutex=1.0=cuda
  - pywin32=311=py312h885b0b7_0
  - pywinpty=2.0.15=py312h72d21ff_0
  - pyyaml=6.0.3=py312hb9a58be_0
  - pyzmq=27.1.0=py312h7149c55_1
  - qtconsole=5.7.0=py312haa95532_0
  - qtpy=2.4.3=py312haa95532_0
  - referencing=0.37.0=py312haa95532_0
  - requests=2.32.5=py312haa95532_1
  - rfc3339-validator=0.1.4=py312haa95532_0
  - rfc3986-validator=0.1.1=py312haa95532_0
  - rpds-py=0.28.0=py312h114bc41_0
  - send2trash=1.8.2=py312haa95532_1
  - setuptools=72.1.0=py312haa95532_0
  - six=1.17.0=py312haa95532_0
  - sniffio=1.3.1=py312haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - stack_data=0.6.3=py312haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - terminado=0.18.1=py312haa95532_0
  - tinycss2=1.4.0=py312haa95532_0
  - tk=8.6.15=hf199647_0
  - traitlets=5.14.3=py312haa95532_0
  - typing-extensions=4.15.0=py312haa95532_0
  - typing_extensions=4.15.0=py312haa95532_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.5.0=py312haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.13=py312haa95532_0
  - webencodings=0.5.1=py312haa95532_2
  - wheel=0.45.1=py312haa95532_0
  - widgetsnbextension=4.0.14=py312haa95532_0
  - win_inet_pton=1.1.0=py312haa95532_1
  - winpty=0.4.3=4
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=h6c54ac7_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - adv-lib==0.2.2
      - anyio==4.12.0
      - autoattack==0.1
      - beautifulsoup4==4.14.3
      - click==8.3.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - eagerpy==0.30.0
      - fonttools==4.61.1
      - foolbox==3.3.4
      - fsspec==2025.10.0
      - gdown==5.1.0
      - geotorch==0.3.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - hf-xet==1.2.0
      - huggingface-hub==1.1.7
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - kiwisolver==1.4.9
      - matplotlib==3.10.8
      - pandas==2.3.3
      - pyparsing==3.3.1
      - pytz==2025.2
      - robustbench==1.1
      - safetensors==0.7.0
      - scipy==1.16.3
      - shellingham==1.5.4
      - smmap==5.0.2
      - soupsieve==2.8
      - sympy==1.13.1
      - timm==1.0.22
      - torchaudio==2.5.1
      - torchdiffeq==0.2.5
      - torchvision==0.20.1
      - tornado==6.5.2
      - tqdm==4.67.1
      - typer-slim==0.20.0
      - tzdata==2025.2
      - visdom==0.2.4
      - websocket-client==1.9.0
